color: yellow
fieldLayouts:
  c0d92897-db22-49be-974c-56ec3017caa1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-21T11:34:05+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 049215a6-0809-4ded-8628-d744442ba388
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-21T11:37:30+00:00'
            elementCondition: null
            fieldUid: 36dca454-5bf3-422e-b397-abb58dda5bbc # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 12496b7a-492c-49d2-920f-70ed92cae716
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-21T11:37:30+00:00'
            elementCondition: null
            fieldUid: 7104f57b-112f-4c96-84cf-eda1c75fe796 # Textfield
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: caf879af-32f8-4f98-bd3a-8f41982b1435
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6f167188-2895-4059-b531-5cd128731cec
        userCondition: null
handle: cardExample
hasTitleField: true
icon: layer-group
name: 'Card Example'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
