color: yellow
fieldLayouts:
  273181ee-c034-4747-bed3-46045cfb92e1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-21T10:05:26+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: fda1bacd-92aa-4d24-bbac-f3510fcbd4a2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-28T16:15:44+00:00'
            elementCondition: null
            fieldUid: 98de0a7d-6346-4ee5-bf70-c8b79372fcec # Text Block
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0741b9fe-17cc-4e00-af4e-2b6d500537b4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-28T16:13:58+00:00'
            elementCondition: null
            fieldUid: 9c06d481-577e-43eb-b499-8393ae38056b # Gallerie Struktur
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e81ebbae-62a0-4006-9e87-f4f465dadf07
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 39f38808-3305-4ff0-9e0a-6b3748da4678
        userCondition: null
handle: gallerie
hasTitleField: true
icon: align-justify
name: Gallerie
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
