color: null
fieldLayouts:
  4f0cd2dd-6dd6-43c2-beab-94d3cb06d105:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-28T15:55:25+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 311402c1-575b-4d08-9f33-c2bc92255197
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-28T15:57:49+00:00'
            elementCondition: null
            fieldUid: 8404cdb2-8675-4b1e-9efa-a7f9aab0c835 # Slider Bilder
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0f3e365a-d2cd-4be1-b9d4-e114e9bd42f1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-28T15:57:49+00:00'
            elementCondition: null
            fieldUid: 98de0a7d-6346-4ee5-bf70-c8b79372fcec # Text Block
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6deaf2f4-afa0-48d0-921f-0c9b5c1752db
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e5bd7351-7aa7-495d-af2b-1d8c63e8af68
        userCondition: null
handle: panelSlider
hasTitleField: true
icon: ''
name: 'Panel Slider'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
