color: null
fieldLayouts:
  5295ecfb-5609-445b-922e-1120592ca6c8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-28T15:56:53+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: eabf36fb-887c-4078-a1bc-eae02092680a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-28T15:59:02+00:00'
            elementCondition: null
            fieldUid: 98de0a7d-6346-4ee5-bf70-c8b79372fcec # Text Block
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4b6ef475-bf51-469c-8cce-9994030581aa
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-28T15:59:02+00:00'
            elementCondition: null
            fieldUid: 2a6dc1b9-39fd-4acf-89c1-aee725a16ea1 # Tags
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4634cdab-7fa5-4868-bee1-5ddfe584faf0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d2ee4068-640b-415a-8e0e-d1fd02f27ee8
        userCondition: null
handle: panelTags
hasTitleField: true
icon: ''
name: 'Panel Tags'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
