color: null
fieldLayouts:
  a0db1ec0-a7de-4e68-a5cd-72e7772fa2e7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-02-28T15:58:44+00:00'
            elementCondition: null
            fieldUid: a2cae9f8-a8d7-4405-bb16-8546f16f6e4c # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d7e30f59-f60f-4892-9e83-13fa6d8c6006
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9701e6ee-8100-496f-a06d-6062396c2b61
        userCondition: null
handle: tags
hasTitleField: false
icon: ''
name: Tags
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
