baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: master-project
primary: true
siteGroup: de666abc-e71d-43e3-b318-cc6d8044b6b9 # master-project
sortOrder: 1
