altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  f76322d0-ef05-49f6-aaf4-09267ebb69fc:
    cardView:
      - filename
      - height
      - width
      - uid
      - 'layoutElement:0cfaaaf1-5973-4c8f-a91a-3a42edaef851'
      - 'layoutElement:95ffa6d5-64d3-489c-893d-f553c73f5c94'
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-21T10:19:42+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: c9e37db9-6937-4f12-8931-b098c093626d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-21T10:25:49+00:00'
            elementCondition: null
            fieldUid: da87989f-6fba-4fb3-afae-2501b651f019 # Alt Text
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 95ffa6d5-64d3-489c-893d-f553c73f5c94
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-21T10:25:49+00:00'
            elementCondition: null
            fieldUid: bebc23d5-2d50-4499-ae0d-6aa66437be5e # Copyright
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0cfaaaf1-5973-4c8f-a91a-3a42edaef851
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0b29a64e-8d30-4835-af4a-9ee754f3953b
        userCondition: null
fs: images
handle: images
name: Images
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: transforms
transformSubpath: ''
