columnSuffix: null
handle: antwort
instructions: null
name: Antwort
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: 9e20b45e-2af1-481b-a621-a750b9a3affb # all
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
