columnSuffix: null
handle: email
instructions: null
name: Email
searchable: false
settings:
  placeholder: example@email.com
translationKeyFormat: null
translationMethod: none
type: craft\fields\Email
