columnSuffix: null
handle: externalLinkUrl
instructions: null
name: 'External Link URL'
searchable: false
settings:
  maxLength: 255
  showLabelField: false
  showTargetField: true
  typeSettings:
    __assoc__:
      -
        - url
        -
          __assoc__:
            -
              - allowRootRelativeUrls
              - ''
            -
              - allowAnchors
              - ''
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
