columnSuffix: null
handle: textfield
instructions: null
name: Textfield
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: becfe5ca-3a1d-4962-8fc7-30c4caf3a387 # Bold Link
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
