dateModified: 1740752122
email:
  fromEmail: base@left.studio
  fromName: master-project
  transportType: craft\mail\transportadapters\Sendmail
fs:
  data:
    hasUrls: true
    name: Data
    settings:
      path: volumes/data
    type: craft\fs\Local
    url: '@webassets/volumes/data'
  images:
    hasUrls: true
    name: Images
    settings:
      path: volumes/images
    type: craft\fs\Local
    url: /volumes/images
  transforms:
    hasUrls: true
    name: Transforms
    settings:
      path: volumes/transforms
    type: craft\fs\Local
    url: '@webassets/volumes/transforms'
  videos:
    hasUrls: true
    name: Videos
    settings:
      path: volumes/videos
    type: craft\fs\Local
    url: '@webassets/volumes/videos'
meta:
  __names__:
    0c017e24-6889-49f0-bdd2-058a139c9f1d: Data # Data
    1d1e70bf-a278-465e-a64d-dfaa1661e193: Navigation # Navigation
    3a3779ad-ff4a-43ac-9875-963dca20b4b7: Navigation # Navigation
    4c70ff1a-21c6-4f84-81e5-b339b02e6f0d: 'MA Card Title' # MA Card Title
    4f9ce81c-6377-48f1-8b5b-b5b2daefb9c1: 'Phone Number' # Phone Number
    5a93054a-9a30-4b95-873b-9ebec3115909: 'Privacy Policy' # Privacy Policy
    05c6e9dc-1fc7-46a8-bbee-2c8138640bd8: Bold # Bold
    5e0d7bb4-8904-49ac-ac02-07a8b46945db: 'Bold Italic' # Bold Italic
    9cc3eba1-d7d2-478f-ab6d-57505ecbcd66: 'Card Example' # Card Example
    33ac218a-68d4-4791-a392-586037092766: 'Website Logo' # Website Logo
    36dca454-5bf3-422e-b397-abb58dda5bbc: Image # Image
    43dd2356-ba3d-4c0f-9dc7-ef6f8103a49c: Home # Home
    50a058af-57fd-4784-a532-cdf609d93221: About # About
    89a65ca6-59b1-4161-a8ca-e27dc33a1765: 'Website Social Links' # Website Social Links
    599c2594-7f7c-47e8-ab7f-5f15ea9d8f90: 'Textfield with Links' # Textfield with Links
    731c4afc-3bf9-4c58-a826-7db0350cadfd: master-project # master-project
    841c0af1-37d6-429d-a7d8-bbb2c21d8566: About # About
    861c6252-90ad-422d-b3bc-8eb31c71d798: Link # Link
    5228acaf-dbbf-4aac-b0b0-0c1c55e94b4a: 'Website Description' # Website Description
    5365ef59-c050-4702-82ab-876962749a48: 'Website Title' # Website Title
    7104f57b-112f-4c96-84cf-eda1c75fe796: Textfield # Textfield
    8319de11-8b0e-487f-83c2-5032ef70e346: Footer # Footer
    21950e08-1320-46dd-b9f3-8ddae1b3aa50: Images # Images
    69307dd8-eb06-43e3-8188-b4df5b23d2e1: 'Image 800x' # Image 800x
    84547fdc-05c1-4c3c-a280-9b7fb6166e32: 'Card Example' # Card Example
    94105fd8-47a5-4c58-9ac1-b9bdc86ac4e4: 'Image Gallery' # Image Gallery
    1795220b-e9cf-41e2-814d-8c93f5dd0e30: 'External Link URL' # External Link URL
    5416109a-5864-4bdf-9179-ee951c51cfd8: Email # Email
    59142390-27d0-4780-8543-5bcfbef4549e: 'External Link Name' # External Link Name
    a2cae9f8-a8d7-4405-bb16-8546f16f6e4c: Text # Text
    bebc23d5-2d50-4499-ae0d-6aa66437be5e: Copyright # Copyright
    becfe5ca-3a1d-4962-8fc7-30c4caf3a387: 'Bold Link' # Bold Link
    c3b49286-4ca2-4801-9d33-2a3e31e1807d: Home # Home
    c26a36f0-36c6-42c0-99e0-aa0b4303441c: 'Image 1600x' # Image 1600x
    c69f0277-c48d-451a-84c1-2b4423aff544: Imprint # Imprint
    c24954e3-8320-487b-87ac-8923abad84c2: Thumbnail # Thumbnail
    c68104aa-08f5-44a5-a8c0-8aca3fba89eb: General # General
    c88814b8-0f99-4d11-9c11-745f4bcc5468: 'Public Schema' # Public Schema
    ccff5e66-8f82-4233-a6da-2adaf6c97ced: Italic # Italic
    ce490459-dc63-4854-810e-ff2762981c6f: Videos # Videos
    da87989f-6fba-4fb3-afae-2501b651f019: 'Alt Text' # Alt Text
    de666abc-e71d-43e3-b318-cc6d8044b6b9: master-project # master-project
    e65df9b6-f654-4750-b847-46e355ec1c39: 'Website Contact' # Website Contact
    e414d637-e54f-4359-9cf8-cd94185009c4: Imprint # Imprint
    f0d61459-f155-4f36-a8ba-74cafea22385: 'Website Privacy Policy' # Website Privacy Policy
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  cp-field-inspect:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: 'Master Project'
  retryDuration: null
  schemaVersion: 5.5.0.0
  timeZone: America/Los_Angeles
