fieldLayouts:
  2caa2653-3e02-4c78-a3d6-1d35a060249c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-21T11:16:13+00:00'
            elementCondition: null
            fieldUid: 1d1e70bf-a278-465e-a64d-dfaa1661e193 # Navigation
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dee3fe35-01d3-436c-87ad-8f066b34c4e2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-21T11:16:45+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: f71568ac-1dd6-48fd-9e42-0f3c8f7fa1f6
            userCondition: null
          -
            dateAdded: '2024-11-21T11:16:45+00:00'
            elementCondition: null
            fieldUid: 8319de11-8b0e-487f-83c2-5032ef70e346 # Footer
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 455c744a-e4a5-4d7d-8d52-5520b80f7261
            userCondition: null
            warning: null
            width: 100
        name: Navigation
        uid: cc5723ba-7c84-4da6-a5b8-68e5697736bb
        userCondition: null
handle: navigation
name: Navigation
sortOrder: 2
