defaultPlacement: end
enableVersioning: true
entryTypes:
  - 9cc3eba1-d7d2-478f-ab6d-57505ecbcd66 # Card Example
handle: cardExample
maxAuthors: 1
name: 'Card Example'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  731c4afc-3bf9-4c58-a826-7db0350cadfd: # master-project
    enabledByDefault: true
    hasUrls: true
    template: card-example/_entry.twig
    uriFormat: 'card-example/{slug}'
type: channel
