defaultPlacement: end
enableVersioning: true
entryTypes:
  - 43dd2356-ba3d-4c0f-9dc7-ef6f8103a49c # Home
handle: home
maxAuthors: 1
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  731c4afc-3bf9-4c58-a826-7db0350cadfd: # master-project
    enabledByDefault: true
    hasUrls: true
    template: _layouts/index.twig
    uriFormat: __home__
type: single
