defaultPlacement: end
enableVersioning: true
entryTypes:
  - 45623e24-32ca-4e88-8460-ce00e4ced169 # kontakt
handle: kontakt
maxAuthors: 1
name: Kontakt
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  731c4afc-3bf9-4c58-a826-7db0350cadfd: # master-project
    enabledByDefault: true
    hasUrls: true
    template: _layouts/kontakt.twig
    uriFormat: kontakt
type: single
